apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: ocean-compute-operator
  name: ocean-compute-operator
  namespace: ocean-operator-6a138
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: ocean-compute-operator
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ocean-compute-operator
    spec:
      containers:
      - env:
        - name: AWS_ACCESS_KEY_ID
          value: somekey
        - name: AWS_SECRET_ACCESS_KEY
          value: somesecret
        - name: AWS_REGION
          value: us-east-1
        - name: IPFS_OUTPUT
          value: https://ipfs-extended.data-marketplace.io
        - name: IPFS_OUTPUT_PREFIX
          value: https://ipfs-extended.data-marketplace.io/ipfs/
        - name: IPFS_ADMINLOGS
          value: https://ipfs-extended.data-marketplace.io
        - name: IPFS_ADMINLOGS_PREFIX
          value: https://ipfs-extended.data-marketplace.io/ipfs/
        - name: AWS_BUCKET_OUTPUT
          value: outputbucket
        - name: AWS_BUCKET_ADMINLOGS
          value: adminbucket
        - name: IPFS_EXPIRY_TIME
          value: "3600"
        - name: STORAGE_CLASS
          value: slow-3-v2
        - name: LOG_LEVEL
          value: DEBUG
        - name: DEBUG_NO_CLEANUP
          value: "0"
        - name: POD_CONFIGURATION_CONTAINER
          value: b2b-docker-registry.cloud.ext.systems/pod-configuration:nextV
        - name: POD_PUBLISH_CONTAINER
          value: b2b-docker-registry.cloud.ext.systems/pod-publishing:nextV
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              key: POSTGRES_DB
              name: postgres-config
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              key: POSTGRES_USER
              name: postgres-config
        - name: POSTGRES_PASSWORD
          valueFrom:
            configMapKeyRef:
              key: POSTGRES_PASSWORD
              name: postgres-config
        - name: POSTGRES_HOST
          valueFrom:
            configMapKeyRef:
              key: POSTGRES_HOST
              name: postgres-config
        - name: POSTGRES_PORT
          valueFrom:
            configMapKeyRef:
              key: POSTGRES_PORT
              name: postgres-config
        image: b2b-docker-registry.cloud.ext.systems/operator-engine:nextV
        imagePullPolicy: Always
        name: ocean-compute-operator
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: regcred
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 1001
        runAsNonRoot: true
        runAsUser: 1001
      serviceAccount: db-operator
      serviceAccountName: db-operator
      terminationGracePeriodSeconds: 30
